### ISSUE TITLE
Framework-specific project

### ISSUE THREAD

**Issue by JosephDuffy** [libical/XbICalendar#40]
I've created a [fork of this repository](https://github.com/JosephDuffy/XbICalendar) and modified it to produce a framework, which can then be include in iOS (including Swift) applications. I have also recompiled the static library with bitcode enabled and updated the scripts.

I just wanted to let you guys know that I've done this because:

 - I'd like re-add the app and test targets and code, but they seemed slightly out of date I wanted to make sure there wasn't a project aim I was missing?
 - I'd like to make sure I've got the licensing correct, and that I can use the linked project in a closed-source commercial application?

[https://github.com/JosephDuffy/XbICalendar](https://github.com/JosephDuffy/XbICalendar)

**Comment by ahalls** [comment]
Joseph Duffy,
Just reading through your commentary this is a great contribution to the project.   I would be happy to review a pull request in more detail and bring your changes into the project.   

There are no active changes going as far as I’m aware so feel free to modify the example app, etc … 

The Mozilla Public License support commercial use. 

-- Andrew
 
Mobile Apps To Engage Your Audience

Eagle, Colorado | Mandurah, Western Australia
+1 (301) 404 7263
andrew@galtsoft.com <mailto:andrew@galtsoft.com> 
www.linkedin.com/in/ahalls <http://www.linkedin.com/in/ahalls>

**Comment by JosephDuffy** [comment]
Thank you for the reply Andrew. I'm working on getting a new beta of the app this framework is in finished and released so I can find any little bugs along the way.

I'll look at re-adding the app and tests project and then create a pull request with the changes.

Thank you for creating this project. It's saved me a lot of time and headaches!

I'll close this comment for now and open a pull request in the future.

**Comment by epologee** [comment]
Did you ever get around to creating a pull request with the bitcode enabled libical?

**Comment by ahalls** [comment]
I haven’t seen it ?

-- A

**Comment by JosephDuffy** [comment]
I've not had time to properly merge the code so that the current project (as hosted here) would continue to function. [My fork](https://github.com/JosephDuffy/XbICalendar) is still available, which does have the framework with bitcode enabled, but *only* has that.
